# Site settings
title: "The Pindar Scholia"
author: Patrick Callahan
description: Site for the Pindar Opera Viewer and Doctoral Dissertation
url: "https://prorycallahan.github.io/dissertation" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/Dissertation" # the subpath of your site, e.g. /blog


# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: PRoryCallahan
twitter_username: P_RoryCallahan

# plugins
plugins: [jekyll-paginate]
paginate: 5
